### ISSUE TITLE
a few improvements made

### ISSUE THREAD

**Issue by hbt** [diffsky/chromedotfiles#3]
First off, thank you for your work on this. 

I forked the project and made a few improvements you might be interested in.

## added default.css

works the same as default.js

## loading css earlier 

CSS is now applied instantaneously. No more visible delay. 

## added support to load multiple JS files

can now organize your files and load vendors without having everything meshed into one file.

Example:

```
// load dependencies in that exact order
loadJS(['vendor/jquery.js', 'vendor/jquery-time-ago.js', 'vendor/underscore.js']);

// load and execute my callback
loadJS('vendor/jquery.js', "callback");
function callback() {}


// load and execute my callback in namespace
loadJS('vendor/jquery.js', 'App.callback');
var App = {
  callback: function() {
  }
};

```

## updated readme

Update readme to explain changes + added example directory

Pick and choose whatever you wanna pull into your repo. 
Forked here https://github.com/hbt/chromedotfiles

Take care

**Comment by matthewhadley** [comment]
Thanks for this. I've incorporated the early loading of css, but will hold off on the multiple js file support for now.
