### ISSUE TITLE
appending CSS

### ISSUE THREAD

**Issue by dholdren** [diffsky/chromedotfiles#6]
I'm playing with the CSS injection and added this to a `github.com.css` file:
```
body {
  background-color: #F00;
}
```

But it had no effect. looking at the Elements tab in chrome, I see that it's inserted before the page's CSS
![image](https://user-images.githubusercontent.com/28270/54770932-9bc76300-4bda-11e9-830b-7c897ef26257.png)

So how do I override existing CSS? Shouldn't appending the CSS be the default?  Or maybe there could be a `github.com.append.css` file that is treated differently at the very least?

**Comment by matthewhadley** [comment]
You'll need to add a rule with [higher specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).
