### ISSUE TITLE
Fix description of plugin: Directory for injected files

### ISSUE THREAD

**Issue by Zocker1999NET** [diffsky/chromedotfiles#8]
I just needed a lot of time to figure out, that the description of the addon saying *place files to ~/.chromedotfiles/{domain}.(js|css)* is wrong. You should change this (stored int the manifest.json) and the description of the repository (on GitHub just below the tabs) to something like `{repository}/chromedotfiles/{domain}.(js|css)` so it matches what your README says.

**Comment by matthewhadley** [comment]
I've updated the README and description to be more clear
