### ISSUE TITLE
Doesn't work - outdated?

### ISSUE THREAD

**Issue by ars4l4n** [diffsky/chromedotfiles#9]
Hey,

it doesn't work on the latest Chrome Build (90.0.4430.93) (Official Build) (64-Bit).
I followed the instruction steps and tried creating the 2 example files just as you did but neither of them caused any difference on google.com

Greetings,
ars4l4n

**Comment by matthewhadley** [comment]
Thanks for reporting! I've just tested this on mac/chrome that I have access to - `Version 90.0.4430.212 (Official Build) (x86_64)` which is a slightly higher version number - and it appears to be working (though the css example selector is outdated now).
